### PR TITLE
SD-78: initial workflow setup

### PR DESCRIPTION
**Pull request by domagojlatecki**
Adds Github actions for PR quality check

### CODE REVIEW

**Comment by domagojlatecki** [comment]
@githinho @josipkoncurat Since `native-image-test` task must run on `macos-latest` due to RAM size (Linux & Windows get 7GB, MacOS gets 14GB for workflows), should we also move other tasks in this workflow to `macos-latest` or do we keep them on `ubuntu-latest`?

**Comment by githinho** [comment]
Use `ubuntu-latest` whenever possible because it is the cheapest option:
```
Operating system | Minute multiplier
Linux | 1
macOS | 10
Windows | 2
```

**Review by githinho — APPROVED** [review]

**Comment by domagojlatecki** [comment]
Ok, I will leave everything as-is then. I tried running native image build on `ubuntu-latest` but it does not offer enough RAM for a successful build.

**Comment by githinho** [comment]
No problem. There no limit on usage for public repo but also no need to use more resources than we need.

**Pull request merged**
